### ISSUE TITLE
Unable to fetch categories and meu-items data.

### ISSUE THREAD

**Issue by Sunny-unik** [TechDevSubhopriyo/Coursera-HTML-CSS-JavaScript#1]
# Description

Unable to fetch categories and menu-items data from API(https://davids-restaurant.herokuapp.com/)

## Screenshot

![image](https://github.com/TechDevSubhopriyo/Coursera-HTML-CSS-JavaScript/assets/65410458/34a3a5c2-2f6f-4281-9757-111346012ed6)

**Comment by Sunny-unik** [comment]
Hi, @TechDevSubhopriyo, you can assign this issue to me or you can use my [new API](https://node-in-docker.onrender.com/) because the present API failed to respond.

**Comment by TechDevSubhopriyo** [comment]
Thank you for finding this issue.

It looks like there was some some problem regarding CORs policy, which I
fixed in my browser for testing. Generally these issues get fixed in
production server. If you are able to provide a better solution, I am happy
to assign this to you.

Regards
Subhopriyo

**Comment by TechDevSubhopriyo** [comment]
It looks like the previous api was taken down.

**Comment by Sunny-unik** [comment]
Yup, maybe because that API is hosted on the free plan of [Heroku](https://www.heroku.com/home).
